# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPagRuedaDLV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200, null=True)),
                ('posicion', models.CharField(choices=[('1', 'primera'), ('2', 'segunda')], default='1', max_length=1)),
                ('area', models.CharField(choices=[('1', 'Carrera|Empresa'), ('2', 'Finanzas|Dinero'), ('3', 'Salud|Vitalidad'), ('4', 'Familia|Amigos'), ('5', 'Amor|relaciones'), ('6', 'Crecimiento personal|Aprendizaje'), ('7', 'Diversion|Estilo de vida'), ('8', 'Productividad personal')], default='1', max_length=1)),
            ],
        ),
    ]
