# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPagRuedaDLV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='area',
            field=models.CharField(choices=[('1', 'Carrera Empresa'), ('2', 'Finanzas Dinero'), ('3', 'Salud Vitalidad'), ('4', 'Familia Amigos'), ('5', 'Amor relaciones'), ('6', 'Crecimiento personal Aprendizaje'), ('7', 'Diversion Estilo de vida'), ('8', 'Productividad personal')], default='1', max_length=1),
        ),
    ]
