# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPagRuedaDLV', '0002_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='amor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='carrera',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='crecimiento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='diversion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='familia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='finanzas',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='gaptotal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='productividad',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='salud',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide10',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide11',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide12',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide13',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide14',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide15',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide16',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide8',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='slide9',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
