# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPagRuedaDLV', '0003_auto_20180629_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='text1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text10',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text11',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text12',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text13',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text14',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text15',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text16',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text8',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='text9',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
