# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPagRuedaDLV', '0003_auto_20180604_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='respuestas',
            new_name='Respuesta',
        ),
    ]
