# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPagRuedaDLV', '0005_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correo',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='correo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='correo',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='usuario',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='correo',
            name='apellidos',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
