# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-01 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eneagrama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoUno', models.IntegerField(null=True)),
                ('tipoDos', models.IntegerField(null=True)),
                ('tipoTres', models.IntegerField(null=True)),
                ('tipoCuatro', models.IntegerField(null=True)),
                ('tipoCinco', models.IntegerField(null=True)),
                ('tipoSeis', models.IntegerField(null=True)),
                ('tipoSiete', models.IntegerField(null=True)),
                ('tipoOcho', models.IntegerField(null=True)),
                ('tipoNueve', models.IntegerField(null=True)),
                ('eneatipoPrincipal', models.CharField(choices=[('1', 'Perfeccionista'), ('2', 'Colaborador'), ('3', 'Competitivo'), ('4', 'Creativo'), ('5', 'Anal\xedtico'), ('6', 'Comprometido'), ('7', 'Din\xe1mico'), ('8', 'L\xedder'), ('9', 'Conciliador')], max_length=1)),
                ('eneatipoSecundario', models.CharField(choices=[('1', 'Perfeccionista'), ('2', 'Colaborador'), ('3', 'Competitivo'), ('4', 'Creativo'), ('5', 'Anal\xedtico'), ('6', 'Comprometido'), ('7', 'Din\xe1mico'), ('8', 'L\xedder'), ('9', 'Conciliador')], max_length=1)),
                ('eneatipoTerciario', models.CharField(choices=[('1', 'Perfeccionista'), ('2', 'Colaborador'), ('3', 'Competitivo'), ('4', 'Creativo'), ('5', 'Anal\xedtico'), ('6', 'Comprometido'), ('7', 'Din\xe1mico'), ('8', 'L\xedder'), ('9', 'Conciliador')], max_length=1)),
                ('centro', models.CharField(choices=[('1', 'Emocional'), ('2', 'F\xedsico'), ('3', 'Intelectual')], max_length=1)),
                ('energia', models.CharField(choices=[('1', 'Interna'), ('2', 'Externa'), ('3', 'Equilibrio')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=1)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_user_set', to='Eneagrama.Evaluacion')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_user_set', to='Eneagrama.Usuario'),
        ),
    ]
