# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-01 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eneagrama', '0003_auto_20180831_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='valor',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
