# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eneagrama', '0004_auto_20180831_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='centroEmocional',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='centroFisico',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='centroIntelectual',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='energiaEquilibrio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='energiaExterna',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='energiaInterna',
            field=models.IntegerField(null=True),
        ),
    ]
