# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eneagrama', '0005_auto_20180902_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(null=True)),
                ('centro', models.CharField(choices=[('1', 'Emocional'), ('2', 'F\xedsico'), ('3', 'Intelectual')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Eneatipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(null=True)),
                ('eneatipo', models.CharField(choices=[('1', 'Perfeccionista'), ('2', 'Colaborador'), ('3', 'Competitivo'), ('4', 'Creativo'), ('5', 'Anal\xedtico'), ('6', 'Comprometido'), ('7', 'Din\xe1mico'), ('8', 'L\xedder'), ('9', 'Conciliador')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Energia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(null=True)),
                ('energia', models.CharField(choices=[('1', 'Interna'), ('2', 'Externa'), ('3', 'Equilibrio')], max_length=1)),
            ],
        ),
    ]
