# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Eneagrama', '0006_centro_eneatipo_energia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
