# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eneagrama', '0007_evaluacion_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
