# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eneagrama', '0008_usuario_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='centro',
            new_name='centroPrimario',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='energia',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='centroSecundario',
            field=models.CharField(choices=[('1', 'Emocional'), ('2', 'F\xedsico'), ('3', 'Intelectual')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='centroTerciario',
            field=models.CharField(choices=[('1', 'Emocional'), ('2', 'F\xedsico'), ('3', 'Intelectual')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='energiaPrimaria',
            field=models.CharField(choices=[('1', 'Interna'), ('2', 'Externa'), ('3', 'Equilibrio')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='energiaSecundatia',
            field=models.CharField(choices=[('1', 'Interna'), ('2', 'Externa'), ('3', 'Equilibrio')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='energiaTerciaria',
            field=models.CharField(choices=[('1', 'Interna'), ('2', 'Externa'), ('3', 'Equilibrio')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='energia',
            name='energia',
            field=models.CharField(choices=[('1', 'Perfeccionista'), ('2', 'Colaborador'), ('3', 'Competitivo'), ('4', 'Creativo'), ('5', 'Anal\xedtico'), ('6', 'Comprometido'), ('7', 'Din\xe1mico'), ('8', 'L\xedder'), ('9', 'Conciliador')], max_length=1),
        ),
    ]
