# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eneagrama', '0009_auto_20180903_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='energiaSecundatia',
            new_name='energiaSecundaria',
        ),
    ]
