# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-04 03:35
from __future__ import unicode_literals

import Eneagrama.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eneagrama', '0011_auto_20180903_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('importe', models.DecimalField(decimal_places=3, max_digits=15)),
                ('tipo_pago', models.CharField(choices=[('0', 'Taller.'), ('1', 'Gratis.'), ('2', 'PayPal.'), ('1', 'Deposito o Transferencia bancaria.')], default='1', max_length=1)),
                ('imagen_comprobante', models.ImageField(null=True, upload_to=Eneagrama.models.unique_file_path)),
                ('metodo_pago', models.CharField(blank=True, choices=[('0', 'No es deposito a bancos no necesita comprobante.'), ('01', 'Efectivo.'), ('02', 'Cheque.'), ('03', 'Transferencia Electronica.')], default='0', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante_user_set', to='Eneagrama.Usuario'),
        ),
    ]
