# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-10 20:04
from __future__ import unicode_literals

import Eneagrama.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eneagrama', '0012_auto_20181003_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puesto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='imagen_comprobante',
            field=models.ImageField(blank=True, null=True, upload_to=Eneagrama.models.unique_file_path),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='tipo_pago',
            field=models.CharField(choices=[('0', 'Taller.'), ('1', 'Gratis.'), ('2', 'PayPal.'), ('3', 'Deposito o Transferencia bancaria.')], default='1', max_length=1),
        ),
    ]
