# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-24 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eneagrama', '0014_auto_20181010_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
