# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-24 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eneagrama', '0015_codigo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('0', 'No es deposito a bancos no necesita comprobante.'), ('01', 'Efectivo.'), ('02', 'Cheque.'), ('03', 'Transferencia Electronica.')], default='0', max_length=2),
        ),
    ]
