# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-01 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eneagrama', '0017_auto_20181031_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='evaluacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_pago_set', to='Eneagrama.Evaluacion'),
        ),
    ]
